name: self-checker
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.0
  - ipython=8.20.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.12.1
  - python-dateutil=2.8.2
  - python_abi=3.12
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.0.3
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023d
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.2.0
      - attrs==23.2.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dataclasses-json==0.6.3
      - distro==1.9.0
      - filelock==3.13.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - joblib==1.3.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.2
      - langchain-community==0.0.14
      - langchain-core==0.1.14
      - langsmith==0.0.83
      - marshmallow==3.20.2
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nltk==3.8.1
      - numpy==1.26.3
      - openai==0.28.0
      - py==1.11.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - retry==0.9.2
      - safetensors==0.4.1
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - sniffio==1.3.0
      - sqlalchemy==2.0.25
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tiktoken==0.5.2
      - tokenizers==0.15.1
      - tqdm==4.66.1
      - transformers==4.37.0
      - typing-inspect==0.9.0
      - urllib3==2.1.0
      - yarl==1.9.4
